FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json 
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Expose port
EXPOSE 3004

# Start the service
CMD ["node", "server.js"]